import { AnalysisResult } from "./types";

export const DEMO_RESULT: AnalysisResult = {
  pageTitle: "Free Webinar: Build a 6-Figure Online Course",
  pageType: "webinar",
  detectedSections: [
    { type: "hero", content: "Join 10,000+ Entrepreneurs Who Have Built 6-Figure Online Courses with the Mirasee ACES Method", confidence: "high" },
    { type: "subheadline", content: "Free Live Training — Thursday, April 10th at 2PM ET", confidence: "high" },
    { type: "problem", content: "Struggling to turn your expertise into a profitable online course? You've tried everything but students just aren't buying.", confidence: "high" },
    { type: "benefits", content: "Discover the 4-step ACES framework, Learn how to price your course, Get our proven launch checklist", confidence: "high" },
    { type: "framework", content: "The ACES Method: Audience → Content → Engagement → Sales", confidence: "medium" },
    { type: "speaker", content: "Danny Iny, Founder of Mirasee — taught over 60,000 entrepreneurs how to build successful online courses", confidence: "high" },
    { type: "testimonials", content: "I went from zero to $127,000 in my first launch using the ACES method — Sarah K., Course Creator", confidence: "high" },
    { type: "agenda", content: "Part 1: Why most courses fail | Part 2: The ACES framework | Part 3: Live Q&A with Danny", confidence: "medium" },
    { type: "faq", content: "Is this really free? Yes. Will there be a replay? No. How long is the webinar? 90 minutes.", confidence: "high" },
    { type: "cta", content: "Yes! Save My Spot — Register Free Now", confidence: "high" },
  ],
  layouts: [
    {
      id: "layout-1",
      name: "Bold Impact",
      description: "High-contrast hero with immediate CTA above the fold",
      colorScheme: "blue",
      style: "bold",
      ctaPosition: "multiple",
      sections: [
        { sectionType: "hero", layout: "full-width", content: "Bold headline + immediate CTA on dark blue background", accentColor: "#F97316" },
        { sectionType: "problem", layout: "full-width", content: "Empathy statement — 'You're not alone if you're struggling...'", accentColor: "#1E3A8A" },
        { sectionType: "benefits", layout: "3-col", content: "3 key outcomes they'll get from the webinar", accentColor: "#1E3A8A" },
        { sectionType: "framework", layout: "full-width", content: "ACES Method visual breakdown with numbered steps", accentColor: "#F97316" },
        { sectionType: "speaker", layout: "split", content: "Danny Iny photo left, bio and credentials right", accentColor: "#1E3A8A" },
        { sectionType: "testimonials", layout: "3-col", content: "3 student success stories with photos and results", accentColor: "#F97316" },
        { sectionType: "agenda", layout: "full-width", content: "What we'll cover — timeline with icons", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Register Free → urgency + date/time reminder", accentColor: "#F97316" },
        { sectionType: "faq", layout: "accordion", content: "5 key objections addressed in collapsible format", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Final CTA — last chance to register", accentColor: "#F97316" },
      ],
    },
    {
      id: "layout-2",
      name: "Clean Authority",
      description: "Whitespace-rich, credibility-first approach",
      colorScheme: "blue",
      style: "minimal",
      ctaPosition: "bottom",
      sections: [
        { sectionType: "headline", layout: "full-width", content: "Centered headline with white background and blue accent underline", accentColor: "#1E3A8A" },
        { sectionType: "subheadline", layout: "full-width", content: "Date/time and key promise in clean serif-inspired layout", accentColor: "#64748B" },
        { sectionType: "speaker", layout: "split", content: "Large speaker photo with trust badges and credentials", accentColor: "#1E3A8A" },
        { sectionType: "benefits", layout: "2-col", content: "Benefit list with checkmarks — clean, readable for 40+ audience", accentColor: "#16A34A" },
        { sectionType: "framework", layout: "full-width", content: "Horizontal step timeline with icons", accentColor: "#1E3A8A" },
        { sectionType: "testimonials", layout: "full-width", content: "Large featured testimonial with photo and full quote", accentColor: "#F97316" },
        { sectionType: "faq", layout: "accordion", content: "FAQ in clean accordion — no visual clutter", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Single strong CTA with urgency and guarantee badge", accentColor: "#F97316" },
      ],
    },
    {
      id: "layout-3",
      name: "Social Proof Engine",
      description: "Card-heavy layout maximizing trust and credibility",
      colorScheme: "blue",
      style: "card-heavy",
      ctaPosition: "multiple",
      sections: [
        { sectionType: "hero", layout: "split", content: "Headline left, registration form right on hero", accentColor: "#F97316" },
        { sectionType: "benefits", layout: "card-grid", content: "6-card benefit grid with icons and short descriptions", accentColor: "#1E3A8A" },
        { sectionType: "testimonials", layout: "3-col", content: "3 testimonial cards with star ratings and photos", accentColor: "#F97316" },
        { sectionType: "speaker", layout: "split", content: "Speaker card with credibility stats: 60K+ students, 12 years", accentColor: "#1E3A8A" },
        { sectionType: "agenda", layout: "card-grid", content: "3-card agenda overview with time + topic per card", accentColor: "#1E3A8A" },
        { sectionType: "testimonials", layout: "3-col", content: "Second row of testimonials — more diverse results", accentColor: "#F97316" },
        { sectionType: "faq", layout: "2-col", content: "FAQ in 2-column card layout for better scanability", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Bold orange CTA with social proof number: Join 10,000+", accentColor: "#F97316" },
      ],
    },
    {
      id: "layout-4",
      name: "Story Journey",
      description: "Narrative flow — takes reader on an emotional journey",
      colorScheme: "blue",
      style: "story",
      ctaPosition: "middle",
      sections: [
        { sectionType: "headline", layout: "full-width", content: "Story hook headline — 'What if you could...'", accentColor: "#1E3A8A" },
        { sectionType: "problem", layout: "full-width", content: "Detailed problem narrative — empathize deeply", accentColor: "#DC2626" },
        { sectionType: "framework", layout: "full-width", content: "The turning point — introducing the ACES solution", accentColor: "#1E3A8A" },
        { sectionType: "benefits", layout: "2-col", content: "Before vs After comparison layout", accentColor: "#16A34A" },
        { sectionType: "speaker", layout: "full-width", content: "Danny's personal story — why he built this method", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Mid-page CTA — 'Ready to join us?'", accentColor: "#F97316" },
        { sectionType: "testimonials", layout: "full-width", content: "Full-width success story with image and detailed journey", accentColor: "#F97316" },
        { sectionType: "agenda", layout: "full-width", content: "What your 90 minutes will look like", accentColor: "#1E3A8A" },
        { sectionType: "faq", layout: "accordion", content: "Objection handling in story tone — conversational FAQ", accentColor: "#1E3A8A" },
        { sectionType: "cta", layout: "full-width", content: "Final CTA with full guarantee and urgency", accentColor: "#F97316" },
      ],
    },
  ],
  conversionScore: {
    headlineClarity: "Strong",
    benefitStructure: "Strong",
    ctaPlacement: "Medium",
    trustElements: "Medium",
    overallScore: 72,
    suggestions: [
      "Add a CTA button earlier — within the first screen view, before the benefits section",
      "Include 2–3 specific testimonials with measurable results (e.g. '$47K in first launch')",
      "Add a countdown timer or registration deadline to increase urgency above the fold",
    ],
  },
};
